version: '3'
volumes:
  pma-session-store:
services:
  web:
    build: ./web
    image: ship-web-image
    hostname: web-server
    container_name: web-customer
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ../:/var/www/app
      - ./web/httpd/app.conf:/etc/httpd/conf.d/app.conf
      - ./web/php/app.ini:/etc/opt/remi/php80/php.ini
    privileged: true
    entrypoint: ["/usr/sbin/init"]

  db:
    build: ./db
    image: ship-db-image
    hostname: db-server
    container_name: db-customer
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: ma123456
      TZ: Asia/Tokyo
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

  pma:
    build: ./phpMyAdmin
    image: phpmyadmin/phpmyadmin
    hostname: pma-server
    container_name: phpmyadmin-customer
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: db
      # PMA_USER: app
      # PMA_PASSWORD: 123456
    volumes:
      - pma-session-store:/sessions
